[package]
name = "histfilesimp"
version = "1.0.0"
edition = "2021"
description = "A script to reduce zsh history"
license = "MIT"
authors = ["SirenityK"]


[[bin]]
name = "histfilesimp"
path = "src/main.rs"

[profile.release]
strip = true
opt-level = "z"
lto = true
panic = "abort"

[package.metadata.deb]
maintainer = "SirenityK"
